/**
 * Centralized Backend Message Codes
 * All user-facing messages from the backend use stable codes.
 * The frontend maps these codes to translation keys based on the selected locale.
 */

const MESSAGE_CODES = {
  // Auth messages
  AUTH_REGISTERED: 'AUTH_REGISTERED',
  AUTH_LOGGED_IN: 'AUTH_LOGGED_IN',
  AUTH_LOGGED_OUT: 'AUTH_LOGGED_OUT',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_OTP_SENT: 'AUTH_OTP_SENT',
  AUTH_OTP_VERIFIED: 'AUTH_OTP_VERIFIED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_PROFILE_FETCHED: 'AUTH_PROFILE_FETCHED',
  AUTH_PROFILE_UPDATED: 'AUTH_PROFILE_UPDATED',
  DASHBOARD_LOADED: 'DASHBOARD_LOADED',
  AUTH_VERIFICATION_REQUIRED: 'AUTH_VERIFICATION_REQUIRED',
  AUTH_VERIFICATION_EXPIRED: 'AUTH_VERIFICATION_EXPIRED',

  // Cart messages
  CART_FETCHED: 'CART_FETCHED',
  CART_ITEM_ADDED: 'CART_ITEM_ADDED',
  CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
  CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
  CART_CLEARED: 'CART_CLEARED',

  // Order messages
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_FETCHED: 'ORDER_FETCHED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_TRACKED: 'ORDER_TRACKED',
  ORDER_RETURN_REQUESTED: 'ORDER_RETURN_REQUESTED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  RETURN_SUBMITTED: 'RETURN_SUBMITTED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',

  // Payment messages
  PAYMENT_ORDER_CREATED: 'PAYMENT_ORDER_CREATED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_ALREADY_VERIFIED: 'PAYMENT_ALREADY_VERIFIED',
  PAYMENT_DETAILS_FETCHED: 'PAYMENT_DETAILS_FETCHED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Coupon messages
  COUPON_APPLIED: 'COUPON_APPLIED',
  COUPON_REMOVED: 'COUPON_REMOVED',
  COUPON_FETCHED: 'COUPON_FETCHED',
  COUPON_AVAILABLE_FETCHED: 'COUPON_AVAILABLE_FETCHED',
  COUPON_VALIDATED: 'COUPON_VALIDATED',
  COUPON_CART_TOTALS: 'COUPON_CART_TOTALS',

  // Wishlist messages
  WISHLIST_FETCHED: 'WISHLIST_FETCHED',
  WISHLIST_ITEM_ADDED: 'WISHLIST_ITEM_ADDED',
  WISHLIST_ITEM_REMOVED: 'WISHLIST_ITEM_REMOVED',

  // Notification messages
  NOTIFICATIONS_FETCHED: 'NOTIFICATIONS_FETCHED',
  NOTIFICATION_MARKED_READ: 'NOTIFICATION_MARKED_READ',
  NOTIFICATION_ALL_MARKED_READ: 'NOTIFICATION_ALL_MARKED_READ',
  NOTIFICATION_DELETED: 'NOTIFICATION_DELETED',
  NOTIFICATIONS_CLEARED: 'NOTIFICATIONS_CLEARED',
  UNREAD_COUNT_FETCHED: 'UNREAD_COUNT_FETCHED',

  // Review messages
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
  REVIEW_FETCHED: 'REVIEW_FETCHED',
  REVIEW_COUNTS_FETCHED: 'REVIEW_COUNTS_FETCHED',

  // Contact messages
  CONTACT_MESSAGE_SENT: 'CONTACT_MESSAGE_SENT',

  // Product messages
  PRODUCTS_FETCHED: 'PRODUCTS_FETCHED',
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',

  // Category messages
  CATEGORIES_FETCHED: 'CATEGORIES_FETCHED',

  // Offer messages
  OFFERS_FETCHED: 'OFFERS_FETCHED',

// Smart Home messages
  SMART_HOME_PLAN_SUBMITTED: 'SMART_HOME_PLAN_SUBMITTED',
  SMART_HOME_PLAN_FETCHED: 'SMART_HOME_PLAN_FETCHED',
  SMART_HOME_STEP_SAVED: 'SMART_HOME_STEP_SAVED',
  SMART_HOME_SESSION_FOUND: 'SMART_HOME_SESSION_FOUND',
  DEMO_ENQUIRY_SUBMITTED: 'DEMO_ENQUIRY_SUBMITTED',
  BACK_IN_STOCK_SUBSCRIBED: 'BACK_IN_STOCK_SUBSCRIBED',
  BACK_IN_STOCK_ALREADY_AVAILABLE: 'BACK_IN_STOCK_ALREADY_AVAILABLE',
  BACK_IN_STOCK_CANCELLED: 'BACK_IN_STOCK_CANCELLED',
  RECENTLY_VIEWED_FETCHED: 'RECENTLY_VIEWED_FETCHED',
  RECENTLY_VIEWED_RECORDED: 'RECENTLY_VIEWED_RECORDED',
  RECENTLY_VIEWED_REMOVED: 'RECENTLY_VIEWED_REMOVED',
RECENTLY_VIEWED_CLEARED: 'RECENTLY_VIEWED_CLEARED',
  WEBSITE_REVIEW_SUBMITTED: 'WEBSITE_REVIEW_SUBMITTED',

  // Search messages
  SEARCH_READY: 'SEARCH_READY',
  SEARCH_RESULTS_FETCHED: 'SEARCH_RESULTS_FETCHED',

  // General messages
  GENERIC_SUCCESS: 'GENERIC_SUCCESS',
  GENERIC_ERROR: 'GENERIC_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_SESSION: 'INVALID_SESSION',
  ADMIN_AUTH_REQUIRED: 'ADMIN_AUTH_REQUIRED',
  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',
  INVALID_ADMIN_SESSION: 'INVALID_ADMIN_SESSION',
};

/**
 * Maps message codes to frontend translation keys
 */
const CODE_TO_TRANSLATION_KEY = {
  AUTH_REGISTERED: 'auth.registeredSuccess',
  AUTH_LOGGED_IN: 'auth.loggedInSuccess',
  AUTH_LOGGED_OUT: 'auth.loggedOutSuccess',
  AUTH_PASSWORD_CHANGED: 'auth.passwordChanged',
  AUTH_PASSWORD_MISMATCH: 'auth.passwordMismatch',
  AUTH_OTP_SENT: 'auth.otpSent',
  AUTH_OTP_VERIFIED: 'auth.otpVerified',
  AUTH_OTP_INVALID: 'auth.invalidOtp',
  AUTH_OTP_EXPIRED: 'auth.otpExpired',
  AUTH_PROFILE_FETCHED: 'auth.profileFetched',
  AUTH_PROFILE_UPDATED: 'auth.profileUpdated',
  DASHBOARD_LOADED: 'dashboard.welcome',
  AUTH_VERIFICATION_REQUIRED: 'auth.verificationRequired',
  AUTH_VERIFICATION_EXPIRED: 'auth.verificationExpired',

  CART_FETCHED: 'cart.fetched',
  CART_ITEM_ADDED: 'cart.itemAdded',
  CART_ITEM_UPDATED: 'cart.itemUpdated',
  CART_ITEM_REMOVED: 'cart.itemRemoved',
  CART_CLEARED: 'cart.cleared',

  ORDER_PLACED: 'order.placedSuccess',
  ORDER_FETCHED: 'order.fetched',
  ORDER_UPDATED: 'order.updated',
  ORDER_CANCELLED: 'order.cancelled',
  ORDER_NOT_FOUND: 'order.notFound',
  ORDER_TRACKED: 'order.tracked',
  ORDER_RETURN_REQUESTED: 'order.returnRequested',
  ORDER_REFUNDED: 'order.refunded',
  ORDER_ALREADY_PAID: 'payment.alreadyVerified',
  RETURN_SUBMITTED: 'return.submitted',
  REFUND_PROCESSED: 'refund.processed',

  PAYMENT_ORDER_CREATED: 'payment.orderCreated',
  PAYMENT_VERIFIED: 'payment.verified',
  PAYMENT_ALREADY_VERIFIED: 'payment.alreadyVerified',
  PAYMENT_DETAILS_FETCHED: 'payment.detailsFetched',
  PAYMENT_FAILED: 'payment.failed',

  COUPON_APPLIED: 'coupon.applied',
  COUPON_REMOVED: 'coupon.removed',
  COUPON_FETCHED: 'coupon.fetched',
  COUPON_AVAILABLE_FETCHED: 'coupon.availableFetched',
  COUPON_VALIDATED: 'coupon.validated',
  COUPON_CART_TOTALS: 'coupon.cartTotals',

  WISHLIST_FETCHED: 'wishlist.fetched',
  WISHLIST_ITEM_ADDED: 'wishlist.itemAdded',
  WISHLIST_ITEM_REMOVED: 'wishlist.itemRemoved',

  NOTIFICATIONS_FETCHED: 'notifications.fetched',
  NOTIFICATION_MARKED_READ: 'notifications.markedRead',
  NOTIFICATION_ALL_MARKED_READ: 'notifications.allMarkedRead',
  NOTIFICATION_DELETED: 'notifications.deleted',
  NOTIFICATIONS_CLEARED: 'notifications.cleared',
  UNREAD_COUNT_FETCHED: 'notifications.unreadCountFetched',

  REVIEW_SUBMITTED: 'review.submitted',
  REVIEW_FETCHED: 'review.fetched',
  REVIEW_COUNTS_FETCHED: 'review.countsFetched',

  CONTACT_MESSAGE_SENT: 'contact.messageSent',

  PRODUCTS_FETCHED: 'product.fetched',
  PRODUCT_FETCHED: 'product.singleFetched',
  PRODUCT_NOT_FOUND: 'product.notFound',

  CATEGORIES_FETCHED: 'category.fetched',
  OFFERS_FETCHED: 'offers.fetched',

SMART_HOME_PLAN_SUBMITTED: 'smartHome.planSubmitted',
  SMART_HOME_PLAN_FETCHED: 'smartHome.planFetched',
  SMART_HOME_STEP_SAVED: 'planner.saved',
  SMART_HOME_SESSION_FOUND: 'planner.sessionFound',
  DEMO_ENQUIRY_SUBMITTED: 'demo.submitted',
  BACK_IN_STOCK_SUBSCRIBED: 'backInStock.subscribed',
  BACK_IN_STOCK_ALREADY_AVAILABLE: 'backInStock.alreadyAvailable',
  BACK_IN_STOCK_CANCELLED: 'backInStock.cancelled',
  RECENTLY_VIEWED_FETCHED: 'recentlyViewed.fetched',
  RECENTLY_VIEWED_RECORDED: 'recentlyViewed.recorded',
  RECENTLY_VIEWED_REMOVED: 'recentlyViewed.removed',
RECENTLY_VIEWED_CLEARED: 'recentlyViewed.cleared',
  WEBSITE_REVIEW_SUBMITTED: 'review.websiteSubmitted',
  SEARCH_READY: 'product.fetched',
  SEARCH_RESULTS_FETCHED: 'product.fetched',

  GENERIC_SUCCESS: 'common.success',
  GENERIC_ERROR: 'common.error',
  VALIDATION_ERROR: 'common.validationError',
  UNAUTHORIZED: 'common.unauthorized',
  FORBIDDEN: 'common.forbidden',
  NOT_FOUND: 'common.notFound',
  SERVER_ERROR: 'common.serverError',
  AUTH_REQUIRED: 'common.unauthorized',
  INVALID_TOKEN: 'auth.invalidSession',
  INVALID_SESSION: 'auth.invalidSession',
  ADMIN_AUTH_REQUIRED: 'common.unauthorized',
  ADMIN_FORBIDDEN: 'common.forbidden',
  INVALID_ADMIN_SESSION: 'auth.invalidSession',
};

const MESSAGE_TEXT_TO_CODE = {
  'Registration successful! Welcome to Tek Node.': MESSAGE_CODES.AUTH_REGISTERED,
  'Registration successful! Please login.': MESSAGE_CODES.AUTH_REGISTERED,
  'Logged in successfully': MESSAGE_CODES.AUTH_LOGGED_IN,
  'Login successful': MESSAGE_CODES.AUTH_LOGGED_IN,
  'Logged out successfully': MESSAGE_CODES.AUTH_LOGGED_OUT,
  'Logout successful': MESSAGE_CODES.AUTH_LOGGED_OUT,
  'Password changed successfully': MESSAGE_CODES.AUTH_PASSWORD_CHANGED,
  'Password reset successfully. Please login with your new password.': MESSAGE_CODES.AUTH_PASSWORD_CHANGED,
  'OTP sent to your email': MESSAGE_CODES.AUTH_OTP_SENT,
  'OTP verified successfully': MESSAGE_CODES.AUTH_OTP_VERIFIED,
  'Profile fetched': MESSAGE_CODES.AUTH_PROFILE_FETCHED,
  'Profile updated': MESSAGE_CODES.AUTH_PROFILE_UPDATED,
  'Dashboard loaded': MESSAGE_CODES.DASHBOARD_LOADED,
  'Cart fetched': MESSAGE_CODES.CART_FETCHED,
  'Cart fetched successfully': MESSAGE_CODES.CART_FETCHED,
  'Product added to cart': MESSAGE_CODES.CART_ITEM_ADDED,
  'Item added to cart': MESSAGE_CODES.CART_ITEM_ADDED,
  'Cart updated': MESSAGE_CODES.CART_ITEM_UPDATED,
  'Cart item updated': MESSAGE_CODES.CART_ITEM_UPDATED,
  'Item removed from cart': MESSAGE_CODES.CART_ITEM_REMOVED,
  'Cart item removed': MESSAGE_CODES.CART_ITEM_REMOVED,
  'Cart cleared': MESSAGE_CODES.CART_CLEARED,
  'Order placed successfully': MESSAGE_CODES.ORDER_PLACED,
  'Order created successfully': MESSAGE_CODES.ORDER_PLACED,
  'Order fetched': MESSAGE_CODES.ORDER_FETCHED,
  'Orders fetched': MESSAGE_CODES.ORDER_FETCHED,
  'Order found': MESSAGE_CODES.ORDER_FETCHED,
  'Order updated': MESSAGE_CODES.ORDER_UPDATED,
  'Order cancelled': MESSAGE_CODES.ORDER_CANCELLED,
  'Order tracked': MESSAGE_CODES.ORDER_TRACKED,
  'Return requested': MESSAGE_CODES.ORDER_RETURN_REQUESTED,
  'Return request submitted. Our team will contact you shortly.': MESSAGE_CODES.ORDER_RETURN_REQUESTED,
  'Order already paid': MESSAGE_CODES.ORDER_ALREADY_PAID,
  'Payment marked failed; coupon restored': MESSAGE_CODES.PAYMENT_FAILED,
  'Payment order created': MESSAGE_CODES.PAYMENT_ORDER_CREATED,
  'Payment verified successfully': MESSAGE_CODES.PAYMENT_VERIFIED,
  'Payment already verified': MESSAGE_CODES.PAYMENT_ALREADY_VERIFIED,
  'Payment details fetched': MESSAGE_CODES.PAYMENT_DETAILS_FETCHED,
  'Payment failed': MESSAGE_CODES.PAYMENT_FAILED,
'Coupon applied successfully': MESSAGE_CODES.COUPON_APPLIED,
  'Coupon removed': MESSAGE_CODES.COUPON_REMOVED,
  'Coupons fetched': MESSAGE_CODES.COUPON_FETCHED,
  'Coupon fetched': MESSAGE_CODES.COUPON_FETCHED,
  'My coupons fetched': MESSAGE_CODES.COUPON_FETCHED,
  'Dashboard coupons & offers fetched': MESSAGE_CODES.COUPON_FETCHED,
  'Offers & coupons fetched': MESSAGE_CODES.COUPON_FETCHED,
  'Available coupons fetched': MESSAGE_CODES.COUPON_AVAILABLE_FETCHED,
  'Coupon validated': MESSAGE_CODES.COUPON_VALIDATED,
  'Cart totals calculated': MESSAGE_CODES.COUPON_CART_TOTALS,
  'Cart totals': MESSAGE_CODES.COUPON_CART_TOTALS,
  'Razorpay order created': MESSAGE_CODES.PAYMENT_ORDER_CREATED,
'Wishlist fetched': MESSAGE_CODES.WISHLIST_FETCHED,
  'Added to wishlist': MESSAGE_CODES.WISHLIST_ITEM_ADDED,
  'Removed from wishlist': MESSAGE_CODES.WISHLIST_ITEM_REMOVED,
  'Notifications fetched': MESSAGE_CODES.NOTIFICATIONS_FETCHED,
  'Your notifications fetched': MESSAGE_CODES.NOTIFICATIONS_FETCHED,
  'Notification marked as read': MESSAGE_CODES.NOTIFICATION_MARKED_READ,
  'All notifications marked as read': MESSAGE_CODES.NOTIFICATION_ALL_MARKED_READ,
  'Notifications marked as read': MESSAGE_CODES.NOTIFICATION_ALL_MARKED_READ,
  'Notification deleted': MESSAGE_CODES.NOTIFICATION_DELETED,
  'All notifications cleared': MESSAGE_CODES.NOTIFICATIONS_CLEARED,
  'Notifications cleared': MESSAGE_CODES.NOTIFICATIONS_CLEARED,
  'Unread count fetched': MESSAGE_CODES.UNREAD_COUNT_FETCHED,
  'Review submitted successfully': MESSAGE_CODES.REVIEW_SUBMITTED,
  'Review submitted successfully. Awaiting admin approval.': MESSAGE_CODES.REVIEW_SUBMITTED,
  'Thank you! Your review has been submitted and is awaiting admin approval.': MESSAGE_CODES.REVIEW_SUBMITTED,
  'Reviews fetched': MESSAGE_CODES.REVIEW_FETCHED,
  'Review fetched': MESSAGE_CODES.REVIEW_FETCHED,
  'Public reviews fetched': MESSAGE_CODES.REVIEW_FETCHED,
  'Review counts fetched': MESSAGE_CODES.REVIEW_COUNTS_FETCHED,
  "Message sent successfully! We'll get back to you soon.": MESSAGE_CODES.CONTACT_MESSAGE_SENT,
  'Products fetched': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Active products fetched': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Products fetched for comparison': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Products fetched by application': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Trending products fetched': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Application counts fetched': MESSAGE_CODES.PRODUCTS_FETCHED,
  'Product fetched': MESSAGE_CODES.PRODUCT_FETCHED,
  'Categories fetched': MESSAGE_CODES.CATEGORIES_FETCHED,
  'Offers fetched': MESSAGE_CODES.OFFERS_FETCHED,
  'Search ready': MESSAGE_CODES.SEARCH_READY,
  'Search results fetched': MESSAGE_CODES.SEARCH_RESULTS_FETCHED,
  'Your smart home plan has been submitted successfully!': MESSAGE_CODES.SMART_HOME_PLAN_SUBMITTED,
  'Smart Home Proposal created successfully': MESSAGE_CODES.SMART_HOME_PLAN_SUBMITTED,
  'Plan fetched': MESSAGE_CODES.SMART_HOME_PLAN_FETCHED,
  'Step saved successfully': MESSAGE_CODES.SMART_HOME_STEP_SAVED,
  'Session found': MESSAGE_CODES.SMART_HOME_SESSION_FOUND,
  'Session retrieved successfully': MESSAGE_CODES.SMART_HOME_SESSION_FOUND,
  'Your demo enquiry has been submitted successfully! We will contact you shortly.': MESSAGE_CODES.DEMO_ENQUIRY_SUBMITTED,
  'Demo request submitted successfully. Our team will contact you shortly.': MESSAGE_CODES.DEMO_ENQUIRY_SUBMITTED,
  'Demo request submitted successfully but email notification failed. Our team will still review your request.': MESSAGE_CODES.DEMO_ENQUIRY_SUBMITTED,
  'Demo request submitted successfully.': MESSAGE_CODES.DEMO_ENQUIRY_SUBMITTED,
  'Your demo enquiry has been submitted successfully! We will contact you shortly.': MESSAGE_CODES.DEMO_ENQUIRY_SUBMITTED,
  'Product is already in stock': MESSAGE_CODES.BACK_IN_STOCK_ALREADY_AVAILABLE,
  "We'll notify you when this product is back in stock": MESSAGE_CODES.BACK_IN_STOCK_SUBSCRIBED,
  'Notification cancelled': MESSAGE_CODES.BACK_IN_STOCK_CANCELLED,
  'Recently viewed products fetched': MESSAGE_CODES.RECENTLY_VIEWED_FETCHED,
  'Recently viewed product recorded': MESSAGE_CODES.RECENTLY_VIEWED_RECORDED,
  'Recently viewed product removed': MESSAGE_CODES.RECENTLY_VIEWED_REMOVED,
  'Recently viewed products cleared': MESSAGE_CODES.RECENTLY_VIEWED_CLEARED,
  'Website review submitted successfully. Awaiting admin approval.': MESSAGE_CODES.WEBSITE_REVIEW_SUBMITTED,
};

module.exports = { MESSAGE_CODES, CODE_TO_TRANSLATION_KEY, MESSAGE_TEXT_TO_CODE };
