import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowLeft, Bold, Italic, Underline, List, ListOrdered, Link2, Unlink,
  AlignLeft, AlignCenter, AlignRight, Undo2, Redo2, Save, Eye, Send,
  RotateCcw, Loader2, ShieldCheck, XCircle, X, CheckCircle2, Lock, User,
  AtSign, KeyRound, Type, Mail, Zap, Package, Wallet, Calendar,
} from "lucide-react";
import { Link, useParams } from "react-router-dom";
import apiCall from "../../services/api.js";
import Toast from "../../admin/components/common/Toast.jsx";

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/i;

// Friendly names shown to the admin. These map to the internal variable
// system (e.g. [Name] -> {{user_name}}) so the backend keeps working.
// Only the ones available for the current template are shown.
const FRIENDLY_VARS = [
  { key: "user_name", tag: "Name", help: "Customer's name", icon: User },
  { key: "user_email", tag: "Email", help: "Customer's email", icon: AtSign },
  { key: "otp", tag: "OTP", help: "Verification code generated by the system", icon: KeyRound, system: true },
  { key: "order_id", tag: "Order ID", help: "Customer's order number", icon: Package },
  { key: "order_total", tag: "Order Total", help: "Total order amount", icon: Wallet },
  { key: "refund_amount", tag: "Refund Amount", help: "Amount refunded to the customer", icon: Wallet },
  { key: "cart_link", tag: "Cart Link", help: "Link back to the customer's cart", icon: Link2 },
  { key: "date", tag: "Date", help: "Order or event date", icon: Calendar },
];

// ─────────────────────────────────────────────────────────────────────────────
// Variable chip ⇄ stored {{placeholder}} conversion
// The admin NEVER sees or types technical placeholders. They see friendly tags
// like [Name]. Internally we store {{user_name}} so the backend can replace it.
// ─────────────────────────────────────────────────────────────────────────────
const friendlyVar = (key) => FRIENDLY_VARS.find((f) => f.key === key) || null;

const chipLabel = (key, metaMap) => {
  const f = friendlyVar(key);
  if (f) return `[${f.tag}]`;
  const meta = metaMap[key];
  return meta ? meta.label : key;
};

const chipHtml = (key, metaMap, isProtected) => {
  const prot = isProtected || friendlyVar(key)?.system ? ` data-protected="true"` : "";
  return `<span class="et-var-chip"${prot} data-var="${key}" contenteditable="false">${chipLabel(key, metaMap)}</span>`;
};

const storedToChips = (html, metaMap) =>
  String(html || "").replace(/\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g, (_m, key) => chipHtml(key, metaMap, false));

const chipsToStored = (html) =>
  String(html || "").replace(
    /<span[^>]*class="[^"]*et-var-chip[^"]*"[^>]*data-var="([A-Za-z0-9_]+)"[^>]*>[\s\S]*?<\/span>/g,
    (_m, key) => `{{${key}}}`,
  );

// ─────────────────────────────────────────────────────────────────────────────
// Rich text editor: a normal document editor backed by contentEditable.
// Produces clean HTML internally without ever exposing tags to the admin.
// ─────────────────────────────────────────────────────────────────────────────
function VariableEditor({ id, value, variablesMeta, onChange, multiline, placeholder, onFocused, registerApi }) {
  const editorRef = useRef(null);
  const savedRangeRef = useRef(null);
  const focusedRef = useRef(false);

  const metaMap = useMemo(() => {
    const map = {};
    (variablesMeta || []).forEach((m) => { map[m.key] = m; });
    return map;
  }, [variablesMeta]);

  // Sync the canvas whenever the stored value changes externally (load/reset/
  // save) — but never while the admin is actively typing/editing.
  useEffect(() => {
    if (editorRef.current && !focusedRef.current) {
      editorRef.current.innerHTML = storedToChips(value, metaMap);
    }
  }, [value, metaMap]);

  const emit = () => {
    if (editorRef.current) onChange(chipsToStored(editorRef.current.innerHTML));
  };

  const captureSelection = () => {
    const sel = window.getSelection();
    if (sel && sel.rangeCount > 0 && editorRef.current && editorRef.current.contains(sel.anchorNode)) {
      savedRangeRef.current = sel.getRangeAt(0).cloneRange();
    }
  };

  const exec = (command, val = null) => {
    const el = editorRef.current;
    if (!el) return;
    el.focus();
    const sel = window.getSelection();
    if (savedRangeRef.current && (!sel || sel.rangeCount === 0 || !el.contains(sel.anchorNode))) {
      sel.removeAllRanges();
      sel.addRange(savedRangeRef.current);
    }
    document.execCommand(command, val ? false : false, val || undefined);
    emit();
  };

  const formatBlock = (block) => {
    const el = editorRef.current;
    if (!el) return;
    el.focus();
    document.execCommand("formatBlock", false, block);
    emit();
  };

  const insertLink = () => {
    const url = window.prompt("Enter the link URL", "https://");
    if (url === null) return;
    const value = url.trim();
    if (!value) { exec("unlink"); return; }
    exec("createLink", value);
  };

  const insertVariable = (meta) => {
    const el = editorRef.current;
    if (!el) return;
    el.focus();
    const sel = window.getSelection();
    if (savedRangeRef.current) {
      sel.removeAllRanges();
      sel.addRange(savedRangeRef.current);
    }
    const chip = chipHtml(meta.key, metaMap, Boolean(meta.protected));
    document.execCommand("insertHTML", false, chip);
    emit();
    if (onFocused) onFocused();
  };

  useEffect(() => {
    if (registerApi) {
      registerApi.current = { insertVariable };
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [insertVariable]);

  return (
    <div className="editor-shell">
      <div className="flex items-center gap-1.5 px-2 py-1.5 bg-gray-900/70 border-b border-gray-700 flex-wrap">
        <button type="button" title="Bold" onClick={() => exec("bold")}
          className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
          <Bold size={14} />
        </button>
        <button type="button" title="Italic" onClick={() => exec("italic")}
          className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
          <Italic size={14} />
        </button>
        <button type="button" title="Underline" onClick={() => exec("underline")}
          className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
          <Underline size={14} />
        </button>

        {multiline && (
          <>
            <div className="w-px h-6 bg-gray-700 mx-1" />
            <div className="relative">
              <select
                title="Text style"
                onChange={(e) => { if (e.target.value) formatBlock(e.target.value); e.target.value = ""; }}
                className="appearance-none inline-flex items-center gap-1.5 h-9 pl-2.5 pr-7 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 border border-gray-700 text-xs font-semibold cursor-pointer outline-none"
                defaultValue=""
              >
                <option value="" disabled>Style</option>
                <option value="p">Regular text</option>
                <option value="h1">Heading 1</option>
                <option value="h2">Heading 2</option>
                <option value="h3">Heading 3</option>
              </select>
              <Type size={13} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 pointer-events-none" />
            </div>
            <button type="button" title="Bullet list" onClick={() => exec("insertUnorderedList")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <List size={14} />
            </button>
            <button type="button" title="Numbered list" onClick={() => exec("insertOrderedList")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <ListOrdered size={14} />
            </button>
            <button type="button" title="Align left" onClick={() => exec("justifyLeft")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <AlignLeft size={14} />
            </button>
            <button type="button" title="Align center" onClick={() => exec("justifyCenter")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <AlignCenter size={14} />
            </button>
            <button type="button" title="Align right" onClick={() => exec("justifyRight")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <AlignRight size={14} />
            </button>
            <div className="w-px h-6 bg-gray-700 mx-1" />
            <button type="button" title="Insert link" onClick={insertLink}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <Link2 size={14} />
            </button>
            <button type="button" title="Remove link" onClick={() => exec("unlink")}
              className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
              <Unlink size={14} />
            </button>
          </>
        )}

        <div className="ml-auto flex items-center gap-1.5">
          <button type="button" title="Undo" onClick={() => exec("undo")}
            className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
            <Undo2 size={14} />
          </button>
          <button type="button" title="Redo" onClick={() => exec("redo")}
            className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-gray-800/60 text-gray-300 hover:bg-gray-700 hover:text-white border border-gray-700 text-sm">
            <Redo2 size={14} />
          </button>
        </div>
      </div>

      <div
        ref={editorRef}
        contentEditable
        data-placeholder={placeholder}
        onInput={emit}
        onFocus={() => { focusedRef.current = true; if (onFocused) onFocused(); }}
        onBlur={() => { focusedRef.current = false; }}
        onMouseUp={captureSelection}
        onKeyUp={captureSelection}
        onClick={captureSelection}
        onKeyDown={(e) => { if (!multiline && e.key === "Enter") e.preventDefault(); }}
        suppressContentEditableWarning
        className={`rich-canvas ${multiline ? "rich-canvas-body" : "rich-canvas-subject"}`}
      />
      <style>{`
        .rich-canvas {
          background: #ffffff;
          color: #1f2937;
          font-family: inherit;
          font-size: 15px;
          line-height: 1.65;
          outline: none;
          word-break: break-word;
        }
        .rich-canvas-subject { padding: 8px 14px; min-height: 40px; display: flex; align-items: center; }
        .rich-canvas-subject:empty::before { content: attr(data-placeholder); color: #9ca3af; }
        .rich-canvas-body { padding: 18px 22px; min-height: 340px; }
        .rich-canvas-body:empty::before { content: attr(data-placeholder); color: #9ca3af; }
        .rich-canvas h1 { font-size: 30px; font-weight: 800; margin: 14px 0 8px; color: #111827; }
        .rich-canvas h2 { font-size: 24px; font-weight: 700; margin: 12px 0 8px; color: #111827; }
        .rich-canvas h3 { font-size: 19px; font-weight: 600; margin: 10px 0 6px; color: #111827; }
        .rich-canvas p { margin: 8px 0; }
        .rich-canvas ul, .rich-canvas ol { padding-left: 26px; margin: 8px 0; }
        .rich-canvas a { color: #1d4ed8; text-decoration: underline; }
        .rich-canvas blockquote { border-left: 4px solid #cbd5e1; padding-left: 14px; color: #374151; margin: 10px 0; }
        .et-var-chip {
          display: inline-flex;
          align-items: center;
          gap: 4px;
          background: #e0f2fe;
          color: #0369a1;
          border: 1px solid #7dd3fc;
          border-radius: 8px;
          padding: 0 8px;
          margin: 0 2px;
          font-weight: 600;
          font-size: 14px;
          line-height: 20px;
          cursor: pointer;
          -webkit-user-select: all;
          user-select: all;
          white-space: nowrap;
        }
        .et-var-chip[data-protected="true"] {
          background: #dbeafe;
          border-color: #93c5fd;
          color: #1d4ed8;
        }
      `}</style>
    </div>
  );
}

function StatusBadge({ enabled }) {
  return enabled ? (
    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border bg-emerald-500/10 text-emerald-400 border-emerald-500/30">
      <ShieldCheck size={13} /> Enabled
    </span>
  ) : (
    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border bg-red-500/10 text-red-400 border-red-500/30">
      <XCircle size={13} /> Disabled
    </span>
  );
}

export default function AdminEmailTemplateEditor() {
  const { key } = useParams();
  const [template, setTemplate] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [templateName, setTemplateName] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [isEnabled, setIsEnabled] = useState(true);
  const [saving, setSaving] = useState(false);
  const [resetting, setResetting] = useState(false);
  const [previewing, setPreviewing] = useState(false);
  const [sendingTest, setSendingTest] = useState(false);
  const [insertTarget, setInsertTarget] = useState("body");
  const [testEmail, setTestEmail] = useState("");
  const [testResult, setTestResult] = useState(null);
  const [preview, setPreview] = useState(null);
  const [toast, setToast] = useState(null);
  const [dirty, setDirty] = useState(false);
  const showToast = (message, type = "success") => setToast({ message, type });

  const subjectApiRef = useRef(null);
  const bodyApiRef = useRef(null);

  const variableMeta = useMemo(
    () => (Array.isArray(template?.variables_meta) ? template.variables_meta : []),
    [template],
  );

  const availableVars = useMemo(() => {
    const keys = variableMeta.length > 0
      ? variableMeta.map((m) => m.key)
      : Array.isArray(template?.variables) ? template.variables : [];
    const keySet = new Set(keys.map(String));
    return FRIENDLY_VARS.filter((fv) => keySet.has(fv.key));
  }, [template, variableMeta]);

  const protectedKeys = useMemo(() => {
    if (!template) return [];
    return (Array.isArray(template.protected_variables) ? template.protected_variables : []).map(String);
  }, [template]);

  const hasRequiredOtp = useMemo(
    () => !protectedKeys.includes("otp") || /{{2}\s*otp\s*}{2}/i.test(body),
    [body, protectedKeys],
  );

  useEffect(() => {
    if (!toast) return undefined;
    const timer = window.setTimeout(() => setToast(null), 3600);
    return () => window.clearTimeout(timer);
  }, [toast]);

  const markDirty = () => setDirty(true);

  const loadTemplate = async () => {
    setLoading(true);
    try {
      const json = await apiCall(`/api/admin/email-templates/${encodeURIComponent(key)}`);
      if (json.success) {
        const t = json.data;
        setTemplate(t);
        setTemplateName(t.template_name || "");
        setSubject(t.subject || "");
        setBody(t.body || "");
        setIsEnabled(Boolean(t.is_enabled));
        setTestResult(null);
        setDirty(false);
        setError(null);
      } else {
        setError(json.message || "Unable to load template");
      }
    } catch (err) {
      setError(err.message || "Unable to load template");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { loadTemplate(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [key]);

  const insertVariableInto = (key) => {
    const ref = insertTarget === "subject" ? subjectApiRef : bodyApiRef;
    if (!ref.current) return;
    const meta = variableMeta.find((m) => m.key === key) || { key };
    ref.current.insertVariable(meta);
    markDirty();
  };

  const saveChanges = async () => {
    if (!templateName.trim()) return showToast("Template name cannot be empty", "error");
    if (!subject.trim()) return showToast("Email Subject cannot be empty", "error");
    if (!body.trim()) return showToast("Email Message cannot be empty", "error");

    // The OTP value is generated by the system, so it must stay in the template.
    if (!hasRequiredOtp) {
      return showToast(
        "The OTP is required in this email. Please add it.",
        "error",
      );
    }

    setSaving(true);
    try {
      const json = await apiCall(`/api/admin/email-templates/${encodeURIComponent(key)}`, {
        method: "PUT",
        body: JSON.stringify({ template_name: templateName, subject, body, is_enabled: isEnabled }),
      });
      if (json.success) {
        const warnings = json.data?.warnings?.unknownVariables || [];
        setTemplate(json.data);
        setTemplateName(json.data.template_name || "");
        setSubject(json.data.subject || "");
        setBody(json.data.body || "");
        setIsEnabled(Boolean(json.data.is_enabled));
        setDirty(false);
        if (warnings.length > 0) {
          showToast("Saved successfully. Some of the details are not supported by this email.", "warning");
        } else {
          showToast("Changes saved successfully");
        }
      } else {
        const msg = json.data?.protectedVariableErrors?.length
          ? json.data.protectedVariableErrors[0].message
          : json.message;
        showToast(msg || "Unable to save changes", "error");
      }
    } catch (err) {
      showToast(err.message || "Unable to save changes", "error");
    } finally {
      setSaving(false);
    }
  };

  const resetToDefault = async () => {
    if (!window.confirm("Are you sure you want to reset this template to its default settings?")) return;
    setResetting(true);
    try {
      const json = await apiCall(`/api/admin/email-templates/${encodeURIComponent(key)}/reset`, { method: "POST" });
      if (json.success) {
        setTemplate(json.data);
        setTemplateName(json.data.template_name || "");
        setSubject(json.data.subject || "");
        setBody(json.data.body || "");
        setIsEnabled(Boolean(json.data.is_enabled));
        setDirty(false);
        showToast("Template reset to default");
      } else {
        showToast(json.message || "Reset failed", "error");
      }
    } catch (err) {
      showToast(err.message || "Reset failed", "error");
    } finally {
      setResetting(false);
    }
  };

  const openPreview = async () => {
    setPreviewing(true);
    try {
      const json = await apiCall(`/api/admin/email-templates/${encodeURIComponent(key)}/preview`, {
        method: "POST",
        body: JSON.stringify({ subject, body }),
      });
      if (json.success) {
        setPreview({ subject: json.data.subject, body: json.data.body, unknownVariables: json.data.unknownVariables || [] });
      } else {
        showToast(json.message || "Preview failed", "error");
      }
    } catch (err) {
      showToast(err.message || "Preview failed", "error");
    } finally {
      setPreviewing(false);
    }
  };

  const sendTest = async () => {
    const to = testEmail.trim();
    if (!EMAIL_REGEX.test(to)) return showToast("Enter a valid test recipient email", "error");
    setSendingTest(true);
    setTestResult(null);
    try {
      const json = await apiCall(`/api/admin/email-templates/${encodeURIComponent(key)}/send-test`, {
        method: "POST",
        body: JSON.stringify({ to, subject, body }),
      });
      if (json.success && json.data?.sent) {
        setTestResult({ ok: true, to, message: `Test email sent to ${to}` });
        showToast("Test email sent");
      } else {
        setTestResult({ ok: false, to, message: (json.data?.message || json.message || "Failed to send test email").slice(0, 300) });
        showToast("Test email failed", "error");
      }
    } catch (err) {
      setTestResult({ ok: false, to, message: err.message || "Failed to send test email" });
      showToast("Test email failed", "error");
    } finally {
      setSendingTest(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-3">
        <Loader2 size={30} className="animate-spin text-cyan-400" />
        <p className="text-gray-500 text-sm">Loading...</p>
      </div>
    );
  }

  if (error || !template) {
    return (
      <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-8">
        <p className="text-red-300 font-semibold">{error || "Template not found"}</p>
        <Link to="/admin/email-templates" className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-cyan-400 hover:text-cyan-300 transition">
          <ArrowLeft size={15} /> Back to Email Templates
        </Link>
      </div>
    );
  }

  const isOtpTemplate = protectedKeys.includes("otp");

  return (
    <div className="space-y-6">
      <Toast toast={toast} />
      <div>
        <Link to="/admin/email-templates" className="inline-flex items-center gap-1.5 text-xs font-semibold text-gray-400 hover:text-cyan-400 transition mb-3">
          <ArrowLeft size={14} /> Back to Email Templates
        </Link>
        <p className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">Settings / Email Templates</p>
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div>
            <h2 className="text-2xl font-bold text-white flex items-center gap-3">
              <Mail className="text-cyan-400" size={24} /> {template.template_name || "Email Template"}
            </h2>
            <p className="text-gray-500 text-xs mt-1">{template.trigger || "User email template"}</p>
          </div>
          <div className="flex items-center gap-2">
            <StatusBadge enabled={isEnabled} />
            {dirty && (
              <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border bg-amber-500/10 text-amber-400 border-amber-500/30">
                Unsaved changes
              </span>
            )}
          </div>
        </div>
      </div>

      {isOtpTemplate && (
        <div className="flex items-start gap-3 bg-blue-500/10 border border-blue-500/30 rounded-2xl px-5 py-4">
          <Lock size={18} className="text-blue-400 mt-0.5 shrink-0" />
          <p className="text-blue-200 text-sm font-semibold">
            The system will automatically add the correct OTP. You cannot edit the OTP itself.
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 items-start">
        <div className="xl:col-span-2 space-y-5">
          {/* Template name + status */}
          <section className="bg-black/40 border border-gray-800 rounded-2xl p-6 space-y-5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <label className="block">
                <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500 mb-2">Template Name</span>
                <input
                  type="text"
                  value={templateName}
                  onChange={(e) => { setTemplateName(e.target.value); markDirty(); }}
                  maxLength={200}
                  className="w-full bg-black border border-gray-700 rounded-lg px-4 py-2.5 text-sm text-white focus:border-cyan-500 outline-none transition"
                />
              </label>
              <div>
                <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500 mb-2">Status</span>
                <button
                  type="button"
                  role="switch"
                  aria-checked={isEnabled}
                  onClick={() => { setIsEnabled(!isEnabled); markDirty(); }}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition ${isEnabled ? "bg-emerald-500" : "bg-gray-700"} mt-1`}
                >
                  <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition ${isEnabled ? "translate-x-6" : "translate-x-1"}`} />
                </button>
                <span className={`ml-3 text-sm font-semibold ${isEnabled ? "text-emerald-400" : "text-red-400"}`}>
                  {isEnabled ? "Enabled — emails of this type are sent" : "Disabled — emails of this type are not sent"}
                </span>
              </div>
            </div>

            <div>
              <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500 mb-2">Email Subject</span>
              <VariableEditor
                id="et-subject"
                value={subject}
                variablesMeta={variableMeta}
                onChange={(v) => { setSubject(v); markDirty(); }}
                multiline={false}
                placeholder="Your verification code"
                onFocused={() => setInsertTarget("subject")}
                registerApi={subjectApiRef}
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500">Email Message</span>
                <span className="text-gray-600 text-xs">Type naturally — no coding needed.</span>
              </div>
              <VariableEditor
                id="et-body"
                value={body}
                variablesMeta={variableMeta}
                onChange={(v) => { setBody(v); markDirty(); }}
                multiline
                placeholder="Write your email message here..."
                onFocused={() => setInsertTarget("body")}
                registerApi={bodyApiRef}
              />
              {!hasRequiredOtp && (
                <div className="mt-2 bg-red-500/10 border border-red-500/30 rounded-xl px-4 py-2.5">
                  <p className="text-red-300 text-xs font-semibold">
                    The OTP is required in this email. Please add it.
                  </p>
                </div>
              )}
            </div>
          </section>

          {/* Actions */}
          <div className="flex flex-wrap items-center gap-3">
            <button type="button" onClick={saveChanges} disabled={saving && !dirty}
              className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition disabled:opacity-50 ${
                hasRequiredOtp
                  ? "bg-gradient-to-r from-cyan-500 to-blue-600 text-white hover:from-cyan-400 hover:to-blue-500"
                  : "bg-red-500/20 text-red-300 border border-red-500/40 hover:bg-red-500/30"
              }`}>
              {saving ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />} Save Changes
            </button>
            <button type="button" onClick={openPreview} disabled={previewing}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-gray-800/70 text-gray-200 hover:bg-gray-700 border border-gray-700 rounded-xl text-sm font-semibold disabled:opacity-50">
              {previewing ? <Loader2 size={16} className="animate-spin" /> : <Eye size={16} />} Preview
            </button>
            <button type="button" onClick={resetToDefault} disabled={resetting}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-gray-800/70 text-gray-300 hover:bg-gray-700 border border-gray-700 rounded-xl text-sm font-semibold disabled:opacity-50">
              {resetting ? <Loader2 size={16} className="animate-spin" /> : <RotateCcw size={16} />} Reset to Default
            </button>
          </div>
          <p className="text-gray-500 text-xs">
            This is exactly what your customers will receive when this email is sent.
          </p>
        </div>

        {/* Right column: variables + test email */}
        <div className="space-y-5">
          <section className="bg-black/40 border border-gray-800 rounded-2xl p-5">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2 mb-4">
              <Zap size={16} className="text-cyan-400" /> Add Details
            </h3>
            <div className="mb-4">
              <div className="grid grid-cols-2 gap-2">
                {[
                  { v: "subject", label: "Email Subject" },
                  { v: "body", label: "Email Message" },
                ].map((o) => (
                  <button
                    key={o.v}
                    type="button"
                    onClick={() => setInsertTarget(o.v)}
                    className={`px-3 py-2 rounded-lg text-xs font-semibold border transition ${
                      insertTarget === o.v
                        ? "bg-cyan-500/15 text-cyan-300 border-cyan-500/40"
                        : "bg-gray-900/50 text-gray-400 border-gray-700 hover:text-gray-200"
                    }`}
                  >
                    {o.label}
                  </button>
                ))}
              </div>
            </div>

            {availableVars.length === 0 ? (
              <p className="text-gray-600 text-xs">No details are available for this email.</p>
            ) : (
              <div className="grid grid-cols-1 gap-2">
                {availableVars.map((fv) => {
                  const isProtected = fv.key === "otp";
                  const Icon = fv.icon;
                  return (
                    <button
                      key={fv.key}
                      type="button"
                      onClick={() => insertVariableInto(fv.key)}
                      className="w-full text-left flex items-center gap-3 bg-gray-900/50 border border-gray-700 hover:border-cyan-500/50 hover:bg-gray-800/60 rounded-lg px-3 py-2.5 transition group"
                    >
                      <span className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${isProtected ? "bg-blue-500/10 text-blue-400" : "bg-cyan-500/10 text-cyan-400"}`}>
                        {isProtected ? <Lock size={15} /> : <Icon size={15} />}
                      </span>
                      <span className="min-w-0 flex-1">
                        <span className="block text-sm font-semibold text-white">[{fv.tag}]</span>
                        <span className="block text-[11px] text-gray-500">{fv.help}</span>
                      </span>
                      {isProtected && (
                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 text-[10px] font-bold uppercase tracking-wide shrink-0">
                          <ShieldCheck size={10} /> System
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>
            )}
            <p className="text-gray-600 text-xs mt-3">
              Click a button to add that detail to your email.
            </p>
          </section>

          <section className="bg-black/40 border border-gray-800 rounded-2xl p-5">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2 mb-4">
              <Send size={16} className="text-cyan-400" /> Test Your Email
            </h3>
            <div className="flex items-center gap-2">
              <input
                type="email"
                value={testEmail}
                onChange={(e) => setTestEmail(e.target.value)}
                placeholder="Enter email address"
                className="w-full bg-black border border-gray-700 rounded-lg px-4 py-2.5 text-sm text-white focus:border-cyan-500 outline-none transition flex-1"
              />
              <button
                type="button"
                onClick={sendTest}
                disabled={sendingTest}
                className="inline-flex items-center gap-2 px-4 py-2.5 bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30 border border-cyan-500/30 rounded-lg text-xs font-semibold disabled:opacity-40 whitespace-nowrap"
              >
                {sendingTest ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />} Send Test Email
              </button>
            </div>
            <p className="text-gray-600 text-xs mt-2">
              Send a test email to see how the message looks.
            </p>
            {testResult && (
              <div className={`mt-3 rounded-xl px-3 py-2.5 text-xs border ${testResult.ok ? "bg-emerald-500/10 text-emerald-300 border-emerald-500/30" : "bg-red-500/10 text-red-300 border-red-500/30"}`}>
                {testResult.ok ? <CheckCircle2 size={13} className="inline" /> : <XCircle size={13} className="inline" />} {testResult.message}
              </div>
            )}
          </section>
        </div>
      </div>

      {preview && (
        <div className="fixed inset-0 z-[100] bg-black/70 backdrop-blur-sm flex items-start justify-center overflow-y-auto p-6">
          <div className="w-full max-w-2xl bg-black/70 border border-gray-700 rounded-2xl max-h-[90vh] overflow-y-auto p-6">
            <div className="flex items-center justify-between gap-3 mb-4">
              <div>
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                  <Eye size={18} className="text-cyan-400" /> Email Preview
                </h3>
                <p className="text-gray-500 text-xs mt-1">
                  Shows how the email will look. The OTP is added automatically by the system.
                </p>
              </div>
              <button type="button" onClick={() => setPreview(null)} className="w-9 h-9 rounded-xl bg-gray-800 text-gray-300 hover:bg-gray-700 flex items-center justify-center" aria-label="Close preview">
                <X size={16} />
              </button>
            </div>
            {preview.unknownVariables.length > 0 && (
              <div className="mb-4 bg-amber-500/10 border border-amber-500/30 rounded-xl px-4 py-3">
                <p className="text-amber-200 text-xs">Some of the details added are not supported by this email.</p>
              </div>
            )}
            <div className="mb-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">Email Subject</p>
              <div className="bg-black/40 border border-gray-800 rounded-xl px-4 py-2.5 text-sm font-semibold text-white">{preview.subject}</div>
            </div>
            <p className="text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">Email Message</p>
            <div className="bg-black/40 border border-gray-800 rounded-xl overflow-hidden">
              <div className="w-full border-0 bg-white p-6" dangerouslySetInnerHTML={{ __html: preview.body }} />
            </div>
            <div className="flex justify-end pt-4">
              <button type="button" onClick={() => setPreview(null)} className="px-5 py-2.5 bg-gray-800 text-gray-300 hover:bg-gray-700 rounded-xl text-sm font-semibold">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}